export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const PUT_USER = "PUT_USER";
//CURSOS
export const GET_CURSOS = "GET_CURSOS";
//MATERIAS
export const GET_MATERIAS = "GET_MATERIAS";
export const PUT_MATERIAS = "PUT_MATERIAS";
export const DELETE_MATERIAS = "DELETE_MATERIAS";
//CLASES
export const GET_CLASES = "GET_CLASES";
export const POST_CLASES = "POST_CLASES";
export const PUT_CLASES = "PUT_CLASES";
export const DELETE_CLASES = "DELETE_CLASES";
//ANUNCIOS
export const GET_ANUNCIOS = "GET_ANUNCIOS";
export const POST_ANUNCIOS = "POST_ANUNCIOS";
export const PUT_ANUNCIOS = "PUT_ANUNCIOS";
export const DELETE_ANUNCIOS = "DELETE_ANUNCIOS";